name: E2E Tests

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

jobs:
  GUI_Web:
    name: GUI_Web
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run tests
        continue-on-error: true
        run: |
          cd GUI_Web/
          mvn test -DexecutionAddress="local" -DtargetOperatingSystem="WINDOWS" -DmaximumPerformanceMode="2" -DtargetBrowserName="MicrosoftEdge" -DgenerateAllureReportArchive="true"

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Allure Report
          path: "GUI_Web/generatedReport_*.zip"

      - name: Upload Extent Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Extent Report
          path: "GUI_Web/extent-reports/ExtentReports_*.html"
          
  API:
    name: API
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run tests
        continue-on-error: true
        run: |
          cd API/
          mvn test -DgenerateAllureReportArchive="true"

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Allure Report
          path: "API/generatedReport_*.zip"

      - name: Upload Extent Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Extent Report
          path: "API/extent-reports/ExtentReports_*.html"